[[constraint]]
  branch = "master"
  name = "github.com/auth0/go-jwt-middleware"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.0"

[[constraint]]
  name = "github.com/emicklei/go-restful-openapi"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"
